[package]
name = "http-server"
version = "0.1.0"
authors = ["Prashanth Valekar, Srinivas <srinivas.prashanth.valekar@sap.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
